platform :ios, "9.0"
workspace       "LSYNetworkingDemo"
project "LSYNetworkingDemo.xcodeproj"



target "LSYNetworkingDemo" do
project "LSYNetworkingDemo.xcodeproj"
use_frameworks!

pod 'AFNetworking',  '~> 4.0'
pod 'YYModel',       '~> 1.0.4'
pod 'XMLDictionary', '~> 1.4.1'

end

